Fix invalid comparison operator on PHP 8.0
magento/zf1 pull request #35
Opened 2021-05-12 09:33 UTC by esler

fixes "PHP Fatal error:  Uncaught ValueError: version_compare(): Argument #3 ($operator) must be a valid comparison operator" error message on PHP 8.0

2021-05-26 05:47 UTC, ihor-sviziev approved these changes

2021-09-08 14:19 UTC, andrewbess requested changes
Hello @esler 
Thank you for your contribution here.
Could you please sign CLA to I have had a possibility to process this PR.
Thank you in advance.

2021-09-08 20:31 UTC, esler commented
@andrewbess done

2021-09-09 11:48 UTC, andrewbess approved these changes

2021-09-15 19:53 UTC, merged